### Generate Spreadsheet
POST http://localhost:3000/spreadsheet
Content-Type: application/json

{
  "attributes": [
    {
      "name": "sku",
      "requiredType": "required",
      "dataType": "string",
      "dsco": true
    },
    {
      "name": "brand",
      "requiredType": "required",
      "dataType": "enum",
      "secondaryDataType": "string",
      "possibleValues": [
        "Samsung",
        "Sony",
        "123"
      ]
    }
  ]
}

### Publish Spreadsheet
POST http://localhost:3000/spreadsheet/publish
Content-Type: application/json

{
  "spreadsheetUrl": "https://docs.google.com/spreadsheets/d/1P5jpEM6SPMTMSOxm9tvuFmjVjdK5zzUY-U_CZK5GJJk/edit?rm=minimal#gid=0",
  "attributes": [
    {
      "name": "sku",
      "requiredType": "required",
      "dataType": "string",
      "dsco": true
    },
    {
      "name": "brand",
      "requiredType": "required",
      "dataType": "enum",
      "secondaryDataType": "string",
      "possibleValues": [
        "Samsung",
        "Sony",
        "123"
      ]
    }
  ]
}

###
