### Get Assortments
GET http://localhost:3000/assortments
Content-Type: application/json
cognito-identity-id: us-east-1:4f0ca0fa-1dd2-4872-b118-41cb20813329 #Logged in as Mike's Stuff


### Generate Spreadsheet
POST http://localhost:3000/spreadsheet
Content-Type: application/json
cognito-identity-id: us-east-1:79fea512-29f8-411c-8a20-d48d76726c39 #Logged in as Mike's Stuff

{
  "retailerId": 1000000001,
  "categoryPath": "Shoes"
}

### Publish Spreadsheet
POST http://localhost:3000/spreadsheet/publish
Content-Type: application/json
cognito-identity-id: us-east-1:79fea512-29f8-411c-8a20-d48d76726c39 #Logged in as Mike's Stuff

{
  "retailerId": 1000000001,
  "categoryPath": "Shoes"
}

### update Spreadsheet
POST http://localhost:3000/spreadsheet/update
Content-Type: application/json
cognito-identity-id: us-east-1:79fea512-29f8-411c-8a20-d48d76726c39 #Logged in as Mike's Stuff

{
  "retailerId": 1000000001,
  "categoryPath": "Clothing||Shoes",
  "revert": true
}
