generate-category-spreadsheet:
    handler: api/generate-category-spreadsheet/generate-category-spreadsheet.generateCategorySpreadsheet
    memorySize: 4086 # High memory usage in case downloading hundreds of thousands of items
    timeout: 30
    vpc: ${self:custom.environment.gearman-and-mongo-vpc}
    events:
        - http:
              path: spreadsheet
              method: post
              cors: true
              integration: lambda-proxy
              authorizer: aws_iam
