publish-category-spreadsheet:
    handler: api/publish-category-spreadsheet/publish-category-spreadsheet.publishCategorySpreadsheet
    memorySize: 1024
    timeout: 10
    environment:
        PUBLISH_BOT_NAME: ${self:custom.publishSpreadsheetBotName}
    events:
        - http:
              path: spreadsheet/publish
              method: post
              cors: true
              integration: lambda-proxy
              authorizer: aws_iam
