# If you change this lambda name, update the root serverless.yml
generate-category-spreadsheet:
  handler: bot/generate-category-spreadsheet/generate-category-spreadsheet.generateCategorySpreadsheet
  memorySize: 1024
  timeout: 240
  vpc: ${self:custom.environment.gearman-and-mongo-vpc}
  layers:
    - ${cf:layer-leo-${self:provider.stage}.LeoLambdaLayerQualifiedArn}
