get-channel-override-spreadsheet-upload-url:
    handler: api/get-channel-overrides-spreadsheet-upload-url/get-channel-overrides-spreadsheet-upload-url.getChannelOverridesSpreadsheetUploadUrl
    memorySize: 1024
    timeout: 10
    events:
        - http:
              path: spreadsheet/upload-catalog-channel-overrides/publish
              method: post
              cors: true
              integration: lambda-proxy
              authorizer: aws_iam
