# If you change this lambda name, update the root serverless.yml
publish-category-spreadsheet-bot:
  handler: bot/publish-category-spreadsheet/publish-category-spreadsheet.publishCategorySpreadsheet
  memorySize: 1024
  timeout: 240
  vpc: ${self:custom.environment.gearman-and-mongo-vpc}
  layers:
    - ${cf:layer-leo-${self:provider.stage}.LeoLambdaLayerQualifiedArn}
