get-channel-overrides-upload-url:
    handler: api/get-channel-overrides-upload-url/get-channel-overrides-upload-url.getChannelOverridesSpreadsheetUploadUrl
    memorySize: 1024
    timeout: 10
    events:
        - http:
              path: spreadsheet/channel-overrides/upload-url
              method: post
              cors: true
              integration: lambda-proxy
              authorizer: aws_iam
              cors:
                origins:
                    - https://*.dsco.io
                headers:
                    - Content-Type
                    - X-Amz-Date
                    - Authorization
                    - X-Api-Key
                    - X-Amz-Security-Token
                    - X-Amz-User-Agent
                    - Cache-Control
                allowCredentials: true
                cacheControl: 'private, no-cache, no-store, must-revalidate, proxy-revalidate'
